# 9key_makro_master shield config for nice!nano

# Encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_KEYMAP_SENSORS=y

# OLED display
CONFIG_I2C=y
CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y

# RGB underglow / WS2812
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=210
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=35
